# Exploratory Data Analysis - 2nd Step
    
    Second section of the data mining. 
    For this purpose, the intention is dropping the values of dates that are generating outliers since the date stamp is incorrect

In [97]:
import pandas as pd
import numpy as np
import os

In [99]:
df = pd.read_csv("/home/alexg/Bedu/Project/Dataframe/ks_df_modified_python1.csv")
df.count()

ID                  374860
name                374860
category            374860
main_category       374860
currency            374860
deadline            374860
goal                374860
launched            374860
pledged             374860
state               374860
backers             374860
country             374860
usd pledged         374860
usd_pledged_real    374860
usd_goal_real       374860
dtype: int64

In [108]:
Specdate = df[df.launched != '1970-01-01 01:00:00']
df[df.launched != '1970-01-01 01:00:00']

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374855,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,canceled,1,US,25.0,25.0,50000.00
374856,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,failed,5,US,155.0,155.0,1500.00
374857,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,failed,1,US,20.0,20.0,15000.00
374858,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,failed,6,US,200.0,200.0,15000.00
374859,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,failed,17,US,524.0,524.0,2000.00

In [112]:
Specdate.to_csv('/home/alexg/Bedu/Project/Dataframe/ks_df_modified_python2.csv', index = False)

In [111]:
Specdate.count()

ID                  374853
name                374853
category            374853
main_category       374853
currency            374853
deadline            374853
goal                374853
launched            374853
pledged             374853
state               374853
backers             374853
country             374853
usd pledged         374853
usd_pledged_real    374853
usd_goal_real       374853
dtype: int64